import {StyleSheet} from 'react-native';
import {BaseColor} from '../../config';
import * as Utils from '../../utils';
export default StyleSheet.create({
  container: {
    paddingBottom: -10,
    justifyContent: 'center',
    alignItems: 'center',
    // borderRadius: 10,
    shadowColor: 'black',
    shadowOffset: {width: 1.5, height: 1.5},
    shadowOpacity: 0.2,
    shadowRadius: 1,
    elevation: 1,
    // backgroundColor: 'white',
    marginHorizontal: 30,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#333',
  },
  inputsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  pinCodeContainer: {
    width: 40,
    height: 60,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  pinCodeText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  focusStick: {
    width: '100%',
    height: 2,
    backgroundColor: 'green',
  },
  activePinCodeContainer: {
    borderColor: 'green',
    borderWidth: 2,
  },
  errorText: {
    color: 'red',
    marginBottom: 10,
  },
  button: {
    marginTop: 20,
  },
  instructions: {
    fontSize: 16,
    marginBottom: 16,
    // color: '#333',
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 5,
    backgroundColor: '#fff',
  },
  button: {
    marginTop: 16,
  },
  errormessage: {
    color: '#FF0000',
  },
  placeholderInput: {
    paddingLeft: 40,
  },
  InputContainer: {
    position: 'relative',
  },
  leftIcon: {
    position: 'absolute',
    top: '55%',
    left: '2%',
    transform: [{translateY: -10}],
    zIndex: 1,
    color: BaseColor.kashmir,
  },
  centeredCard: {
    marginTop: 60,
    position: 'absolute',
    top: '15%',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  cardContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOffset: {width: 1.5, height: 1.5},
    shadowOpacity: 0.2,
    shadowRadius: 1,
    elevation: 1,
  },
  InputContainer: {
    position: 'relative',
  },
  appLogo: {
    height: Utils.scaleWithPixel(80),
    width: Utils.scaleWithPixel(90),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 30,
  },
  otpView: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 50,
    borderWidth: 0,
    padding: 20,
    width: '100%',
    // backgroundColor: 'white',
    borderRadius: 10,
    shadowColor: 'black',
    shadowOffset: {width: 1.5, height: 1.5},
    shadowOpacity: 0.1,
    shadowRadius: 0.24,
  },
  bottomImage: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: Utils.scaleWithPixel(200),
    resizeMode: 'cover',
  },
  eyeIconContainer: {
    position: 'absolute',
    top: '50%',
    right: 10,
    transform: [{translateY: -7}],
    zIndex: 2,
  },
});
